//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesforceCon.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalesforceCon.Helper.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountId : {0}  Account created successfully.
        /// </summary>
        internal static string ACCOUNT_CREATE {
            get {
                return ResourceManager.GetString("ACCOUNT_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountId : {0} Account updated successfully.
        /// </summary>
        internal static string ACCOUNT_UPDATE {
            get {
                return ResourceManager.GetString("ACCOUNT_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CampaingId : {0} Campaing created successfully.
        /// </summary>
        internal static string CAMPAING_CREATE {
            get {
                return ResourceManager.GetString("CAMPAING_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactId : {0}  Contact created successfully.
        /// </summary>
        internal static string CONTACT_CREATE {
            get {
                return ResourceManager.GetString("CONTACT_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactId : {0} Contact update successfully.
        /// </summary>
        internal static string CONTACT_UPDATE {
            get {
                return ResourceManager.GetString("CONTACT_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeadId : {0} Lead created successfully.
        /// </summary>
        internal static string LEAD_CREATE {
            get {
                return ResourceManager.GetString("LEAD_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeadId : {0} Lead updated successfully.
        /// </summary>
        internal static string LEAD_UPDATE {
            get {
                return ResourceManager.GetString("LEAD_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpportunityId : {0} Opportunity created successfully.
        /// </summary>
        internal static string OPPORTUNITY_CREATE {
            get {
                return ResourceManager.GetString("OPPORTUNITY_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpportunityId : {0} Opportunity updated successfully.
        /// </summary>
        internal static string OPPORTUNITY_UPDATE {
            get {
                return ResourceManager.GetString("OPPORTUNITY_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesforce object synchronized Successfully.
        /// </summary>
        internal static string SUCCESS_RESPONSE {
            get {
                return ResourceManager.GetString("SUCCESS_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} User created Successfully.
        /// </summary>
        internal static string USER_CREATED {
            get {
                return ResourceManager.GetString("USER_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} has been logged into salesforce connector.
        /// </summary>
        internal static string USER_LOGIN {
            get {
                return ResourceManager.GetString("USER_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} has been logged out from salesforce connector.
        /// </summary>
        internal static string USER_LOGOUT {
            get {
                return ResourceManager.GetString("USER_LOGOUT", resourceCulture);
            }
        }
    }
}
