//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesforceCon.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBConfiguration
    {
        public long Id { get; set; }
        public string FBDataSource { get; set; }
        public string FBInitialCatalog { get; set; }
        public string FBClientId { get; set; }
        public string FBClientPassword { get; set; }
        public string FBPort { get; set; }
        public string FBConnection { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
