//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesforceCon.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestLog
    {
        public int RequestId { get; set; }
        public string OrderId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string RequestModel { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
